Clean up Spin Lock tests
## This Commit

Removes a thread from the Spin Lock loom test and removes some
unnecessary `Arc`s from a non-loom test.

## Why?

Just to remove things that weren't adding value. But the loom test still
doesn't pass so I'm not sure how much I care here. The error is:

```
thread 'spin_lock::tests::vague_loom_test' panicked at 'assertion failed: `(left != right)`
  left: `VersionVec { versions: [2, 65535, 0, 0] }`,
 right: `VersionVec { versions: [2, 65535, 0, 0] }`', /.../.cargo/registry/src/github.com-1ecc6299db9ec823/loom-0.5.6/src/rt/atomic.rs:805:17
```

My vague take on this is:

1. thread `0` is the main test thread
2. thread `1` is the spawned test thread
3. loom tries 2 different versions of how the first thread locks
4. loom's finding lots of different ways to spin the spawned thread and
   eventually maxing out because two consecutive versions are the same
   when they shouldn't be

No idea what to do about this :shrug: